name: cell-vae
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.0.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - aiobotocore==2.23.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - anndata==0.11.4
      - annotated-types==0.7.0
      - array-api-compat==1.12.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - botocore==1.38.27
      - cellxgene-census==1.17.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gget==0.29.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.14.0
      - idna==3.10
      - ipywidgets==8.1.7
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - lxml==6.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - mysql-connector-python==9.3.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pandas==2.3.1
      - patsy==1.0.1
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pyarrow-hotfix==0.7
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - s3fs==2025.7.0
      - scanpy==1.11.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.33.0
      - session-info2==0.1.2
      - shapely==2.1.1
      - smmap==5.0.2
      - somacore==1.0.28
      - soupsieve==2.7
      - statsmodels==0.14.5
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tiledbsoma==1.17.0
      - torch==2.7.1
      - torchmetrics==1.7.4
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wandb==0.21.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - yarl==1.20.1
